### ISSUE TITLE
please add a latest-iso-symlinks for beta images too

### ISSUE THREAD

**Issue by beta-tester** [pentoo/pentoo.github.io#4]
hi,

i have a tiny [RPi-PXE-Server project](https://github.com/beta-tester/RPi-PXE-Server).
the pxe-server will download the Live iso images of different distributions
and offer those images to PCs to PXE-boot into those Live distributions.

your **Pentoo** and **Pentoo Beta** is in the list as well.

for the normal Pentoo LiveDVD iso you have fortunately a symbolic link
"https://pentoo.ch/isos/latest-iso-symlinks/pentoo-amd64-hardened.iso", that always points to the most recent iso image.
that gives me the possibility to keep Pentoo up to date without changing the installation script.
(thank you very much!)
 
but unfortunately you don't have an equal symbolic link for the beta images.
there it would make also sense, because of those iso images tend to get updated in a more higher frequency.

please add something eqal like https://pentoo.ch/isos/Beta/latest-iso-symlinks/...
this would help me alot to keep Live images up to date without changing the script all the time when a new updated iso image is available.

**Comment by blshkv** [comment]
sounds like a good suggestion. Done, thank you.

**Comment by beta-tester** [comment]
the https://pentoo.ch/isos/Beta/latest-iso-symlinks/ you made are gone again.
:-(

**Comment by blshkv** [comment]
@ZeroChaos- please fix it at your end

**Comment by ZeroChaos-** [comment]
Beta symlinks are being automatically created *WHEN AND IF* there are active betas.  which for example right now there is only amd64-hardened.

Beta's are not nightlies, they are not consistent, they are generated on an as needed bases for testing.

I will try to add nightly isos at some point, but please don't confuse betas with something you can rely on.

**Comment by blshkv** [comment]
in short, it is here: https://pentoo.ch/isos/latest-iso-symlinks/Beta/

**Comment by beta-tester** [comment]
just realized, that https://www.pentoo.ch/isos/latest-iso-symlinks/Beta/pentoo-beta-amd64-hardened-latest.iso is **NOT** pointing to the **FULL** version of pentoo beta.

is that intended or a mistake or is simply the symbolic link https://www.pentoo.ch/isos/latest-iso-symlinks/Beta/pentoo-beta-full-amd64-hardened-latest.iso with "**FULL**" missing?

**Comment by blshkv** [comment]
Good point, ZC please fix ALL symlinks (beta/release) and add a symlink to a relevant full image as well

**Comment by beta-tester** [comment]
the symlink https://www.pentoo.ch/isos/latest-iso-symlinks/pentoo-amd64-hardened-latest.iso
is pointing to https://www.pentoo.ch/isos/Pentoo_amd64_hardened/pentoo-amd64-hardened-2018.0_RC8.iso

there is no latest symlink for the FULL version!

(same for the beta as mentioned before)

PS.: happy def con 26 in las vegas... unfortunately i am not there :(

**Comment by beta-tester** [comment]
i'll close that issue, because there are now different symlinks to all the variants of release and beta iso files.
thank you.

**Comment by beta-tester** [comment]
symbolic link to `pentoo-full-amd64-hardened-latest.iso` is broken / gone. 
https://www.pentoo.ch/isos/latest-iso-symlinks/pentoo-full-amd64-hardened-latest.iso

**Comment by ZeroChaos-** [comment]
isos are only linked when they exist. sometimes there isn't a beta

**Comment by blshkv** [comment]
he is not talking about beta version. The link is broken

**Comment by ZeroChaos-** [comment]
fixed, thanks

**Comment by beta-tester** [comment]
@blshkv , @ZeroChaos- ...
thank you for fixing.
