### ISSUE TITLE
"old" webpage & wikipedia

### ISSUE THREAD

**Issue by beta-tester** [pentoo/pentoo.github.io#5]
hi,

when i searching something on the internet, i tend to take a look to wikipedia first.
pentoo in wikipedia shows "https://www.pentoo.ch/" as official webpage.
to me that "https://www.pentoo.ch/" looks a bit outdated and there is not easy to find link available that points out, that pentoo is still alive.
it shows Pentoo 2015.0 RC5 (x86 still on RC4.6) as most recent version.

on wikipedia "https://en.wikipedia.org/wiki/Pentoo" latest versions on the top right side area are also outdated.
on the Releases section there, the link to shapshots is dead.

**Comment by ostree** [comment]
hi,

we spoke some time ago about setting out a cname to use a custom domain name, some docs are here:
https://help.github.com/articles/using-a-custom-domain-with-github-pages/

and info additionally: 
https://github.com/pentoo/pentoo.github.io/blob/master/README.md
 
it is easy to do and up to zero and blshkv 

regarding wikipedia i will take a look and update if outdated, thx for the info,

kind regards

**Comment by blshkv** [comment]
```www.pentoo.ch``` website is the official for now. There is a changelog column which we fix recently, it shows the latest changes. We need to add a commit date as well. We are working on it ;-)
We know we need to fix it, there is no need in such bug reports at this point
