### ISSUE TITLE
too short file names in folder view

### ISSUE THREAD

**Issue by beta-tester** [pentoo/pentoo.github.io#6]
when i browse to the folder view of the directories, the file names appears way too short.
you can not really distinguish the files by the file names those are shown.
![view](https://user-images.githubusercontent.com/4750719/43913543-9f4a6f5c-9c05-11e8-8438-e902e6ae05bf.PNG)

**Comment by ZeroChaos-** [comment]
Patches welcome

**Comment by ghost** [comment]
https://www.daveperrett.com/articles/2008/12/29/styling-apache-directory-listings-with-mod_autoindex/
http://httpd.apache.org/docs/2.2/mod/mod_autoindex.html
https://github.com/ramlmn/Apache-Directory-Listing

**Comment by blshkv** [comment]
this is fixed, thanks!
